title: Sustainable Development Blog # your site title
email: ivo.steimanis@staff.uni-marburg.de  
description: sustainable development blog - insights from behavioral economic research
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://sustuse.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  sustuse # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

# AUTHORS
authors:
  steimani:
        display_name: Ivo Steimanis
        about: Ivo is PhD student in behavioral development economics at the Philipps University Marburg.
        email: mailto:ivo.steimanis@staff.uni-marburg.de
        web: https://www.uni-marburg.de/fb02/sustuse/team/steimanis
        github: https://github.com/tlvoli/
        image: /assets/img/posts/ivo.jpg 
  kampenhu:
        display_name: Lukas Kampenhuber
        about: Lukas is PhD student in behavioral development economics at the Philipps University Marburg. 
        email: mailto:kampenhu@staff.uni-marburg.de
        web: https://www.uni-marburg.de/fb02/sustuse/team/kampenhuber
        image: /assets/img/posts/lukas.jpg
  mayer:
        display_name: Matthias Mayer
        about: Matthias is PhD student in behavioral development economics at the Philipps University Marburg. 
        email: mailto:matthias.mayer@staff.uni-marburg.de
        web: https://www.uni-marburg.de/fb02/sustuse/team/matthias
        image: /assets/img/posts/matthias.jpg
  bartels:
        display_name: Lara Bartels
        about: Lara wrote her master thesis with us and is now pursuing a career outside of academics. 


social:
 name: Research Group for Sustainable Use of Natural Resources
 links:
   - https://www.uni-marburg.de/fb02/sustuse

disqus:
  shortname: sustuse # to enable comments replace with your_disqus_shortname
  
google_tag_manager: GTM-W25H52M

# Build settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
